name: node-project
on:
    push:
        branches:
            main
jobs:
    build:
        name: Initial Setup and Code Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Node Setup
          uses: actions/setup-node@v1
          with:
            node-version: ${{matrix.node-version}}
            cache: "npm"
        - name: Setup Dependencies 
          run: npm install
        - name: Run index file
          run: npm start
    test:
        needs: [build]
        name: Test phase
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Node Setup
          uses: actions/setup-node@v1
          with:
            node-version: ${{matrix.node-version}}
            cache: "npm"
        - name: Setup Dependencies 
          run: npm install
        - name: Test the code
          run: npm test     
                

        


